### ISSUE TITLE
Executables are no longer available in the releases

### ISSUE THREAD

**Issue by agateau** [skim-rs/skim#496] opened 2022-11-10 09:01 UTC
Since version 0.10.0, GitHub releases no longer include executables, contrary to what is mentioned here: https://github.com/lotabout/skim#hard-core.

Is it possible to bring the executables back? If not, then the README should be updated.

**Comment by timvisee** [comment] 2023-01-05 20:10
Duplicate of https://github.com/lotabout/skim/issues/493

**Closed** 2024-11-22 21:43 UTC
