### ISSUE TITLE
No more executables in releases?

### ISSUE THREAD

**Issue by thisismygitrepo** [skim-rs/skim#512] opened 2023-01-01 09:36 UTC
In the README, it says in installation section that one can head to releases to get ready executables. I went there and there's only zipped source code. 

I scrolled down and it seems that back in the day, exe used to come with releases but not any more, can we have them again please?

**Comment by timvisee** [comment] 2023-01-05 19:59
Duplicate of https://github.com/lotabout/skim/issues/496

**Closed** 2024-11-16 19:24 UTC
